cargo-features = ["resolver"]

[package]
name = "learning-opengl"
version = "0.1.0"
authors = ["Will Crichton <wcrichto@cs.stanford.edu>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.7"

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = "0.26"
winit = "0.24"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3"
wasm-bindgen = "0.2"
winit = {version = "0.24", features = ["web-sys"]}
console_error_panic_hook = "0.1"