[env]
ENV_DIR = {source="${CARGO_MAKE_PROFILE}", default_value = "debug", mapping = {release = "release"}}

[env.release]
CARGO_RELEASE_ARGS = "--release"

[tasks.cargo-build-web]
args = ["build", "--target", "wasm32-unknown-unknown", "@@split(CARGO_RELEASE_ARGS, )"]
command = "cargo"

[tasks.build-web]
args = ["--out-dir", "wasm/build", "--target", "web", "target/wasm32-unknown-unknown/${ENV_DIR}/learn-opengl.wasm"]
command = "wasm-bindgen"
dependencies = ["cargo-build-web"]